### ISSUE TITLE
[bug] Possible binary incompatibility numpy==1.21.0

### ISSUE THREAD

**Issue by MatthewPierson90** [jgrss/cultionet#1]
I get the following error running "cultionet create", updating Numpy fixes the error, but I am not sure if that update causes my other issues.

Traceback (most recent call last):
  File "/home/matthew/.pyenv/versions/cultionet2/bin/cultionet", line 5, in <module>
    from cultionet.scripts.cultionet import main
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 13, in <module>
    from cultionet.data.create import create_dataset
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/cultionet/data/create.py", line 11, in <module>
    import geowombat as gw
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/geowombat/__init__.py", line 2, in <module>
    from .core.api import open
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/geowombat/core/__init__.py", line 1, in <module>
    from ..backends import transform_crs
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/geowombat/backends/__init__.py", line 2, in <module>
    from .xarray_ import concat, mosaic
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/geowombat/backends/xarray_.py", line 7, in <module>
    from ..core.windows import get_window_offsets
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/geowombat/core/windows.py", line 1, in <module>
    from .util import n_rows_cols
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/geowombat/core/util.py", line 9, in <module>
    from ..moving import moving_window
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/geowombat/moving/__init__.py", line 1, in <module>
    from ._moving import moving_window
  File "geowombat/moving/_moving.pyx", line 1, in init geowombat.moving._moving
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by jgrss** [comment]
This looks like `geowombat` and `cultionet` were compiled with different numpy versions. Since `cultionet` is pinned to `numpy==1.21.0`, you can try:

```python
pyenv activate your.venv
(your.venv) pip uninstall geowombat -y
(your.venv) cd cultionet/ 
# Re-install cultionet, which will install geowombat and should use numpy==1.21.0 since it's already installed
(your.venv) pip install .
```

My guess is that `geowombat` was installed first and used the most recent version of `numpy`.

**Comment by MatthewPierson90** [comment]
That would make sense! Why does cultionet need GDAL 3.2.1? (I am guessing that is part of why I need an earlier version of geowombat, when I install gdal 3.2.1 geowombat 1.7.4 gets mad, but cultionet is mad if I have gdal 3.3.2) 
I've been running cultionet with GDAL 3.3.2 without much issue, but that might have been the cause of some of the other problems that I had

**Comment by MatthewPierson90** [comment]
I still needed up update numpy with the fresh install, with geowombat 1.8.5 I also ran into an error with a cython compiled file:

 File "src/geowombat/moving/_moving.pyx", line 1, in init geowombat.moving._moving
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).

I added np._import_array to the file suggested, and it works after reinstalling geowombat

**Comment by MatthewPierson90** [comment]
I think I see what is going on with GDAL, geowombat wants the version of GDAL for whatever version the GDAL binaries are,  and in my case that is 3.3.2.

**Comment by jgrss** [comment]
Ah, yes, your Python GDAL version should match your GDAL binaries version.

**Comment by jgrss** [comment]
Closing this because I think this was geowombat/numpy and not necessarily a cultionet issue.
