### ISSUE TITLE
[bug] TypeError: can't convert np.ndarray of type numpy.uint16. 

### ISSUE THREAD

**Issue by MatthewPierson90** [jgrss/cultionet#2]
I get the following error running "cultionet create". The problem is with torch and can be fixed by converting y to an int or float before getting y_

I added the following code to cultionet/data/utils.py at line 58 

if y.dtype == np.uint16:
    y = y.astype(int) # int and not np.int32 since torch will use long anyways

Traceback (most recent call last):
  File "/home/matthew/.pyenv/versions/cultionet2/bin/cultionet", line 8, in <module>
    sys.exit(main())
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 492, in main
    persist_dataset(args)
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 290, in persist_dataset
    create_dataset(
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/cultionet/data/create.py", line 569, in create_dataset
    train_data = augment(
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/cultionet/augment/augmentation.py", line 207, in augment
    return create_data_object(
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/cultionet/data/utils.py", line 58, in create_data_object
    y_ = torch.tensor(y.flatten(), dtype=torch.float if 'float' in y.dtype.name else torch.long)
TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

**Comment by jgrss** [comment]
I think this is fixed [here](https://github.com/jgrss/cultionet/blob/8ab9e6805305b90d6d4866d170fab708b797d02f/src/cultionet/data/utils.py#L87) but feel free to re-open.
