### ISSUE TITLE
[bug] ValueError: `x` must be strictly increasing sequence.

### ISSUE THREAD

**Issue by MatthewPierson90** [jgrss/cultionet#3]
I run into the following error running 'cultionet create' with exactly one veg index. It can be avoided by not doing any time augmentations. I have also gotten the error to go away by making the following edit in augment/augmentations.py line 34

.reshape(nrows*ncols, int(ntime/nbands), nbands)) -> .reshape(nrows*ncols, nbands, int(ntime/nbands)))

I do wonder if this is a result of how my .tif files are saved. If extract them as np.arrays their shape is (1, h, w). 

In your code you have  

Reshape from (T x H x W) -> (H*W x T x C)

I suspect T is for time, C is for channels, you also have variables ntime and nbands.  
If I print out ntime and nbands using 4 time series images (4 can be replaced with n) I get the following results

1 veg index
ntime = 4, nbands=4

2 veg indices:
ntime = 8, nbands=4

This makes me suspect that nbands is really the time variable and ntime is the total number of channels in the dataset. 
This would make int(ntime/nbands) the total number of vegetation indices.  

I haven't attempted to see if I can save the .tif files differently, nor am I sure if I can.

Traceback (most recent call last):
  File "/home/matthew/.pyenv/versions/cultionet2/bin/cultionet", line 8, in <module>
    sys.exit(main())
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 492, in main
    persist_dataset(args)
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 290, in persist_dataset
    create_dataset(
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/cultionet/data/create.py", line 559, in create_dataset
    train_data = augment(
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/cultionet/augment/augmentation.py", line 81, in augment
    xaug = augment_time(
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/cultionet/augment/augmentation.py", line 39, in augment_time
    xseg_warped = warper.augment(xseg)
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/tsaug/_augmenter/base.py", line 189, in augment
    X_aug, Y_aug = self._augment(X, Y)
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/tsaug/_augmenter/base.py", line 252, in _augment
    X_aug[ind, :], Y_aug = self._augment_core(X_aug[ind, :], None)
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/tsaug/_augmenter/time_warp.py", line 167, in _augment_core
    warp = PchipInterpolator(x=anchors, y=anchor_values, axis=1)(
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/scipy/interpolate/_cubic.py", line 232, in __init__
    x, _, y, axis, _ = prepare_input(x, y, axis)
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/scipy/interpolate/_cubic.py", line 61, in prepare_input
    raise ValueError("`x` must be strictly increasing sequence.")
ValueError: `x` must be strictly increasing sequence.

**Comment by MatthewPierson90** [comment]
I've dug a bit more into this.
In create_image_vars lines 323-328, you use gw.open and stack by bands. 
You later compute nbands (line 336), this value is really the number of time steps. nbands gets passed to augment, which is here the above error was occurring. 

I just wanted to double check that this is just a naming convention that you decided to go with and not an error, but computing

ntime = int(src_ts.gw.nbands / len(list(set([Path(fn).parent.name for fn in image]))))

and 

nbands = int(src_ts.gw.nbands/ntime)

fixes the above error.

**Comment by jgrss** [comment]
@MatthewPierson90 Thanks for raising this. Does[ this PR](https://github.com/jgrss/cultionet/pull/19) fix the issue you are seeing?

You are right in the `gw.open` syntax. Here, band is actually loading `time x bands/variables`. I tried to make the variables a bit easier to follow in the docstrings found in the new functions of the PR.

Is [this](https://github.com/jgrss/cultionet/blob/10b8826fc1847e494c81a8dc979da290a667401e/src/cultionet/augment/augmentation.py#L44) the 'reshaping back' error you were seeing? I address that in the PR with `tsaug_to_feature_stack()`.

In
> .reshape(nrowsncols, int(ntime/nbands), nbands)) -> .reshape(nrowsncols, nbands, int(ntime/nbands)))

I now have `(nrows * ncols, int(nfeas / nbands), nbands)`, where `nfeas` are the total number of features (i.e., time x band) and `nbands` are the number of bands, or channels. Thus, `ntime = nfeas / nbands`.

**Comment by MatthewPierson90** [comment]
@jgrss 

I put a comment in the pull request. I wasn't very clear in my second comment, I'm sorry for that. I've also left a comment in the pull request near the specific line.

I'm pretty sure that the way you originally had the time series augmentation was correct, I believe that the error occurs before that in a different script, specifically in

cultionet/data/create.py

around line 336 is where I think the error happened (it is where time and bands got flipped)

**Comment by jgrss** [comment]
Fixed in #19
