### ISSUE TITLE
[bug] TypeError: __init__() got an unexpected keyword argument 'every_n_val_epochs'

### ISSUE THREAD

**Issue by MatthewPierson90** [jgrss/cultionet#4]
I get the following error when running 'cultionet train'.  It can be fixed by changing 

(Line 83) every_n_val_epochs -> every_n_epochs 
in model.py

Traceback (most recent call last):
  File "/home/matthew/.pyenv/versions/cultionet2/bin/cultionet", line 8, in <module>
    sys.exit(main())
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 494, in main
    train_model(args)
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 331, in train_model
    cultionet.fit(
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/cultionet/model.py", line 75, in fit
    cb_train_loss = ModelCheckpoint(
TypeError: __init__() got an unexpected keyword argument 'every_n_val_epochs'

**Comment by jgrss** [comment]
Thanks, `every_n_val_epochs` came from previous PyTorch Lightning versions and I obviously didn't get all of the names updated.

**Comment by jgrss** [comment]
This should be resolved with the latest versions.
