### ISSUE TITLE
[bug] issue with trainer specifically for a cpu device

### ISSUE THREAD

**Issue by MatthewPierson90** [jgrss/cultionet#5]
I get the following error when running 'cultionet train' using --device cpu. I suspect it will be an issue with predict as well.

This issue can be resolved by adding an if then statement to model.py with separate calls to pl.Trainer (rather than setting device to 0 in the trainer call) 

    if device == 'gpu':
        trainer = pl.Trainer(
            default_root_dir=str(ckpt_file.parent),
            callbacks=[
                lr_monitor,
                cb_train_loss,
                cb_val_loss,
                early_stop_callback
            ],
            stochastic_weight_avg=stochastic_weight_avg,
            enable_checkpointing=True,
            auto_lr_find=auto_lr_find,
            auto_scale_batch_size=False,
            accumulate_grad_batches=1,
            gradient_clip_val=gradient_clip_val,
            gradient_clip_algorithm='value',
            check_val_every_n_epoch=1,
            min_epochs=5 if epochs >= 5 else epochs,
            max_epochs=epochs,
            precision=32,
            devices=1 if device == 'gpu' else 0,
            gpus=1 if device == 'gpu' else 0,
            num_processes=0,
            accelerator=device,
            progress_bar_refresh_rate=10,
            log_every_n_steps=10
        )
    elif device == 'cpu':
                trainer = pl.Trainer(
            default_root_dir=str(ckpt_file.parent),
            callbacks=[
                lr_monitor,
                cb_train_loss,
                cb_val_loss,
                early_stop_callback
            ],
            stochastic_weight_avg=stochastic_weight_avg,
            enable_checkpointing=True,
            auto_lr_find=auto_lr_find,
            auto_scale_batch_size=False,
            accumulate_grad_batches=1,
            gradient_clip_val=gradient_clip_val,
            gradient_clip_algorithm='value',
            check_val_every_n_epoch=1,
            min_epochs=5 if epochs >= 5 else epochs,
            max_epochs=epochs,
            precision=32,
            num_processes=0,
            accelerator=device,
            progress_bar_refresh_rate=10,
            log_every_n_steps=10
        )

Traceback (most recent call last):
  File "/home/matthew/.pyenv/versions/cultionet2/bin/cultionet", line 8, in <module>
    sys.exit(main())
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 494, in main
    train_model(args)
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 331, in train_model
    cultionet.fit(
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/cultionet/model.py", line 98, in fit
    trainer = pl.Trainer(
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/pytorch_lightning/utilities/argparse.py", line 339, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 483, in __init__
    self._accelerator_connector = AcceleratorConnector(
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 188, in __init__
    self._check_device_config_and_set_final_flags(
  File "/home/matthew/.pyenv/versions/3.8.12/envs/cultionet2/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 424, in _check_device_config_and_set_final_flags
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: `Trainer(devices=0)` value is not a valid input using cpu accelerator.

**Comment by jgrss** [comment]
There is now a check for `device` and `devices`.
