### ISSUE TITLE
Failing Unittests

### ISSUE THREAD

**Issue by mmann1123** [jgrss/cultionet#60]
@jgrss I am getting an error with untittests after install using the dockerfile for 11.3.  I tried to resolve it but had no luck

~/cultionet/tests$ python -m unittest

```
EE
======================================================================
ERROR: test_create_dataset (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_create_dataset
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/conda/envs/pytorch/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/ubuntu/cultionet/tests/test_create_dataset.py", line 3, in <module>
    from .data import p
ImportError: attempted relative import with no known parent package


======================================================================
ERROR: test_dataset (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_dataset
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/conda/envs/pytorch/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/ubuntu/cultionet/tests/test_dataset.py", line 4, in <module>
    from .data import batch_file
ImportError: attempted relative import with no known parent package


----------------------------------------------------------------------
Ran 2 tests in 0.000s
```

**Comment by jgrss** [comment]
Also, we're releasing `v1.7.0` today from [this branch](https://github.com/jgrss/cultionet/tree/jgrss/topo_v2_time_rnn_nobal_batch_act_dgm_test) if you want to test it in your Docker image.

**Comment by mmann1123** [comment]
I had run:

```
python -m unittest 
```
similar to geopandas

I just tried the suggested `pytest -vv` but getting another set of issues (and yes I have pathlib installed):

```
====================================================================== test session starts =======================================================================
platform linux2 -- Python 2.7.18, pytest-4.6.9, py-1.8.1, pluggy-0.13.0 -- /usr/bin/python2
cachedir: .pytest_cache
rootdir: /home/ubuntu/cultionet
collected 0 items / 6 errors                                                                                                                                     

============================================================================= ERRORS =============================================================================
__________________________________________________________ ERROR collecting tests/test_augmentation.py ___________________________________________________________
ImportError while importing test module '/home/ubuntu/cultionet/tests/test_augmentation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
/usr/lib/python2.7/dist-packages/_pytest/assertion/rewrite.py:304: in load_module
    exec(co, mod.__dict__)
test_augmentation.py:1: in <module>
    from cultionet.augment.augmenters import Augmenters
E   ImportError: No module named cultionet.augment.augmenters
_________________________________________________________ ERROR collecting tests/test_create_dataset.py __________________________________________________________
/usr/lib/python2.7/dist-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
E     File "/home/ubuntu/cultionet/tests/test_create_dataset.py", line 12
E       REGION = f"{CONFIG['regions'][-1]:06d}"
E                                             ^
E   SyntaxError: invalid syntax
_____________________________________________________________ ERROR collecting tests/test_dataset.py _____________________________________________________________
ImportError while importing test module '/home/ubuntu/cultionet/tests/test_dataset.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
/usr/lib/python2.7/dist-packages/_pytest/assertion/rewrite.py:304: in load_module
    exec(co, mod.__dict__)
test_dataset.py:1: in <module>
    from pathlib import Path
E   ImportError: No module named pathlib
______________________________________________________________ ERROR collecting tests/test_loss.py _______________________________________________________________
ImportError while importing test module '/home/ubuntu/cultionet/tests/test_loss.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
/usr/lib/python2.7/dist-packages/_pytest/assertion/rewrite.py:304: in load_module
    exec(co, mod.__dict__)
test_loss.py:1: in <module>
    from cultionet.losses import TanimotoDistLoss
E   ImportError: No module named cultionet.losses
______________________________________________________________ ERROR collecting tests/test_norm.py _______________________________________________________________
/usr/lib/python2.7/dist-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
E     File "/home/ubuntu/cultionet/tests/test_norm.py", line 27
E       def create_small_chips(b: torch.Tensor, rc_slice: tuple) -> Data:
E                               ^
E   SyntaxError: invalid syntax
_____________________________________________________________ ERROR collecting tests/test_reshape.py _____________________________________________________________
ImportError while importing test module '/home/ubuntu/cultionet/tests/test_reshape.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
/usr/lib/python2.7/dist-packages/_pytest/assertion/rewrite.py:304: in load_module
    exec(co, mod.__dict__)
test_reshape.py:1: in <module>
    from pathlib import Path
E   ImportError: No module named pathlib
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 6 errors during collection !!!!!
```

**Comment by jgrss** [comment]
This looks like a environment issue given that everything passes for me locally and on CI and in Docker.

```python
    from cultionet.augment.augmenters import Augmenters
E   ImportError: No module named cultionet.augment.augmenters
```
is only in the upcoming release, so it looks like you installed the branch. However, your `pytest` might be looking somewhere else. Are you running inside a venv?

**Comment by mmann1123** [comment]
It was installed in a conda env that comes with the EC2 deep learning instance.  That's the challenge at the moment.

**Comment by mmann1123** [comment]
I restarted the install and ran through everything with no error. Only major difference is I am using ARM and had to update the cuda install to match.


Here's my install steps - 99% as suggested. 
```
sudo add-apt-repository ppa:graphics-drivers/ppa
sudo apt-get update
sudo apt install ubuntu-drivers-common -y
ubuntu-drivers devices
sudo apt install nvidia-driver-465 -y


https://developer.nvidia.com/cuda-11.3.0-download-archive?target_os=Linux&target_arch=arm64-sbsa&Compilation=Cross&Distribution=Ubuntu&target_version=20.04
#linux
#arm64-sbsa
#cross
#ubuntu
#20.04
#deb local

wget https://developer.download.nvidia.com/compute/cuda/11.3.0/local_installers/cuda-repo-cross-sbsa-ubuntu2004-11-3-local_11.3.0-1_all.deb
sudo dpkg -i cuda-repo-cross-sbsa-ubuntu2004-11-3-local_11.3.0-1_all.deb
sudo apt-key add /var/cuda-repo-cross-sbsa-ubuntu2004-11-3-local/7fa2af80.pub
sudo apt-get update
sudo apt-get -y install cuda-cross-sbsa
 

#install pyenv
curl https://pyenv.run | bash


echo 'export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
' >> ~/.profile

exec "$SHELL"

echo 'export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if which pyenv > /dev/null; then eval "$(pyenv init --path)"; fi
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
if which pyenv > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi' >> ~/.bashrc

echo 'pyenv activate venv.cultionet' >> ~/.bashrc

source ~/.bashrc
exec "$SHELL"

sudo apt-get update; sudo apt-get install make build-essential libssl-dev zlib1g-dev \
libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev -y


pyenv install 3.8.12
pyenv virtualenv 3.8.12 venv.cultionet
pyenv activate venv.cultionet

# other reqs
pip install -U pip setuptools wheel "cython>=0.29.*" "numpy<=1.21.0"
# required to build GDAL Python bindings for 3.2.1
pip install --upgrade --no-cache-dir "setuptools<=58.*"

# pytorch 
pip install torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio==0.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html

sudo reboot


# more dependancies 
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric torch-geometric-temporal -f https://data.pyg.org/whl/torch-1.10.1+cu113.html

# install gdal
sudo add-apt-repository ppa:ubuntugis/ppa
sudo apt install build-essential
sudo apt update
sudo apt install libspatialindex-dev libgdal-dev gdal-bin -y

export CPLUS_INCLUDE_PATH=/usr/include/gdal
export C_INCLUDE_PATH=/usr/include/gdal

pip install GDAL==3.2.1

# install cultionet
git clone https://github.com/jgrss/cultionet.git
cd cultionet
pip install .
```

Tests are failing with:

```
pytest -vv
============================================== test session starts ==============================================
platform linux2 -- Python 2.7.18, pytest-4.6.9, py-1.8.1, pluggy-0.13.0 -- /usr/bin/python2
cachedir: .pytest_cache
rootdir: /home/ubuntu/cultionet
collected 0 items / 6 errors                                                                                    

==================================================== ERRORS =====================================================
__________________________________ ERROR collecting tests/test_augmentation.py __________________________________
ImportError while importing test module '/home/ubuntu/cultionet/tests/test_augmentation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
/usr/lib/python2.7/dist-packages/_pytest/assertion/rewrite.py:304: in load_module
    exec(co, mod.__dict__)
test_augmentation.py:1: in <module>
    from cultionet.augment.augmenters import Augmenters
E   ImportError: No module named cultionet.augment.augmenters
_________________________________ ERROR collecting tests/test_create_dataset.py _________________________________
/usr/lib/python2.7/dist-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
E     File "/home/ubuntu/cultionet/tests/test_create_dataset.py", line 12
E       REGION = f"{CONFIG['regions'][-1]:06d}"
E                                             ^
E   SyntaxError: invalid syntax
____________________________________ ERROR collecting tests/test_dataset.py _____________________________________
ImportError while importing test module '/home/ubuntu/cultionet/tests/test_dataset.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
/usr/lib/python2.7/dist-packages/_pytest/assertion/rewrite.py:304: in load_module
    exec(co, mod.__dict__)
test_dataset.py:1: in <module>
    from pathlib import Path
E   ImportError: No module named pathlib
______________________________________ ERROR collecting tests/test_loss.py ______________________________________
ImportError while importing test module '/home/ubuntu/cultionet/tests/test_loss.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
/usr/lib/python2.7/dist-packages/_pytest/assertion/rewrite.py:304: in load_module
    exec(co, mod.__dict__)
test_loss.py:1: in <module>
    from cultionet.losses import TanimotoDistLoss
E   ImportError: No module named cultionet.losses
______________________________________ ERROR collecting tests/test_norm.py ______________________________________
/usr/lib/python2.7/dist-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
E     File "/home/ubuntu/cultionet/tests/test_norm.py", line 27
E       def create_small_chips(b: torch.Tensor, rc_slice: tuple) -> Data:
E                               ^
E   SyntaxError: invalid syntax
____________________________________ ERROR collecting tests/test_reshape.py _____________________________________
ImportError while importing test module '/home/ubuntu/cultionet/tests/test_reshape.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
/usr/lib/python2.7/dist-packages/_pytest/assertion/rewrite.py:304: in load_module
    exec(co, mod.__dict__)
test_reshape.py:1: in <module>
    from pathlib import Path
E   ImportError: No module named pathlib
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 6 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================ 6 error in 0.42 seconds ============================================
```
I definitely have pathlib, so not sure why that's happening.

**Comment by mmann1123** [comment]
@jgrss  is there some way I can see how they are building the CI instances?

**Comment by jgrss** [comment]
Is this isolated to the tests? I.e., can you run `cultionet train -h`?

And to confirm, are you running
```commandline
cd cultionet/
pip install .
pytest -vv
```
or
```commandline
cd cultionet/
pip install .
pytest tests/ -vv
```
or
```commandline
cd cultionet/
pip install .
cd tests/
pytest -vv
```

**Comment by jgrss** [comment]
>  is there some way I can see how they are building the CI instances?

Probably? Maybe? But really I have no idea.

**Comment by mmann1123** [comment]
I tried running all three variants of pytest for the hell of it. Same 6 errors regardless. 

`cultionet train -h` returns:
Which seems related to: [this maybe](https://stackoverflow.com/questions/73029425/cannot-import-name-resnet50-weights-from-torchvision-models-resnet)

```
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/venv.cultionet/bin/cultionet", line 5, in <module>
    from cultionet.scripts.cultionet import main
  File "/home/ubuntu/.pyenv/versions/3.8.12/envs/venv.cultionet/lib/python3.8/site-packages/cultionet/__init__.py", line 3, in <module>
    from .model import fit, load_model, predict, predict_lightning
  File "/home/ubuntu/.pyenv/versions/3.8.12/envs/venv.cultionet/lib/python3.8/site-packages/cultionet/model.py", line 27, in <module>
    from .models.lightning import (
  File "/home/ubuntu/.pyenv/versions/3.8.12/envs/venv.cultionet/lib/python3.8/site-packages/cultionet/models/lightning.py", line 19, in <module>
    from .maskcrnn import BFasterRCNN
  File "/home/ubuntu/.pyenv/versions/3.8.12/envs/venv.cultionet/lib/python3.8/site-packages/cultionet/models/maskcrnn.py", line 10, in <module>
    from torchvision.models.detection import maskrcnn_resnet50_fpn_v2
ImportError: cannot import name 'maskrcnn_resnet50_fpn_v2' from 'torchvision.models.detection' (/home/ubuntu/.pyenv/versions/3.8.12/envs/venv.cultionet/lib/python3.8/site-packages/torchvision/models/detection/__init__.py)
```
I will try upgrading and see if that resolves it.

**Comment by mmann1123** [comment]
After   `pip install --upgrade torch torchvision`
```
cultionet train -h
Segmentation fault (core dumped)
```

**Comment by jgrss** [comment]
I would try a higher version of `torch`. But, upgrading existing installs can be slightly sensitive with `torch` dependencies, so be sure to uninstall and install per the [PyTorch install page](https://pytorch.org/get-started/locally/). 

1. Optional, but maybe try a higher version of Python.

```commandline
pyenv virtualenv 3.8.15 venv.cultionet
```

2. Clean out PyTorch

```commandline
(venv.cultionet) pip uninstall torch torchvision torchaudio pyg_lib \
    torch_scatter torch_sparse torch_cluster torch_spline_conv torch_geometric cultionet -y
```

3. Install PyTorch

```commandline
TORCH_VERSION="1.12.1"
CUDA_VERSION="cu113"
(venv.cultionet) pip install torch==$TORCH_VERSION torchvision torchaudio \
    --extra-index-url https://download.pytorch.org/whl/${CUDA_VERSION}
```

4. Install PyTorch Geometric

```commandline
(venv.cultionet) pip install pyg_lib torch_scatter torch_sparse \
    torch_cluster torch_spline_conv torch_geometric \
    -f https://data.pyg.org/whl/torch-${TORCH_VERSION}+${CUDA_VERSION}.html
```

6. Install Cultionet

```commandline
(venv.cultionet) cd cultionet/
(venv.cultionet) pip install .
```

**Comment by mmann1123** [comment]
Thanks!! I'm away for the week. But I'll let you know how it goes

**Comment by mmann1123** [comment]
Ok I am passing tests now with the latest version. We can close this.
